[package]
name = "terra"
version = "0.1.0"
edition = "2018"

[dependencies]
thiserror = "1.0"
anyhow = "1.0"
maplit = "1.0"
chrono = "0.4.7"
comrak = "0.6.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8.9"
ring = "0.13.5"
mysql = "16"
rocket = "0.4.2"
rocket_contrib = { version = "0.4.2", features = ["helmet", "serve", "json", "mysql_pool"] }
maud = { version = "0.21.0", features = ["rocket"] }
lettre = "0.9.2"
lettre_email = "0.9.2"
