listen: 127.0.0.1:8000
campaign_path: /home/me/code/terra-data/campaigns/last-bastion
assets_path: /home/me/work/terra-assets/out

auth_db:
  connect: mysql://trinity:trinity@localhost/authchars

chars_db:
  connect: mysql://trinity:trinity@localhost/authchars
